# Node docker image on which this would be run
image: node:18.16.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

# Job 1:
staging-build-main:
  stage: build
  script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - npm install
    # - npm run test
  only:
    staging

# Job 2:
# Deploy to staging
staging-deploy-main:
  image: ruby:latest
  only:
    staging
  stage: deploy
  script:
    - bash deploy/deploy.sh