const express = require("express");
const router = express.Router();
const auth = require('../../middleware/auth');
const analyticController = require('../../controllers/analytic');
router.post('/calculator_stats',auth,analyticController.calculatorStats);
router.post('/visitor_key',analyticController.generateVisitor);
router.post('/saveLead',analyticController.saveLead);
router.post('/get_engagements',auth,analyticController.fetchVisitors);
router.post('/get_leads',auth,analyticController.get_leads);
router.post('/delete_visits',auth, analyticController.deleteVisitors);
// router.post('/delete_leads',auth, analyticController.deleteLead);
module.exports=router;
