module.exports.v1Route=require("./v1.route")
module.exports.builderRoute=require("./builder.route")
module.exports.frontendRoute=require("./frontend.route")
module.exports.liveRoute=require("./live.route")
module.exports.analytic=require("./analytic.route")