const express = require("express");
const router = express.Router();
const adminController = require('../../../controllers/admin/dashboard');
const adminUserController = require('../../../controllers/admin/user');
const adminAuth = require('../../../middleware/adminauth');
router.get('/getfeatureLists', adminController.getFeatureLists);
router.get('/getfeatureLists',adminController.getFeatureLists);
router.post('/login',adminUserController.loginUser);
router.get('/checkUser',adminAuth,adminUserController.checkUser);
router.get('/getfeatureList/:id', adminController.getFeatureListById);
router.post('/createFeatureList', adminController.createFeatureList);
router.put('/updateFeatureList/:id', adminController.updateFeatureList);
router.patch('/updateActiveStatus/:id', adminController.toggleActiveStatus);
router.get('/getUsersCount', adminController.getUsersCount);
router.get('/getFeaturesCount', adminController.getFeaturesCount);
router.get('/getLeadsCount', adminController.getLeadsCount);
router.get('/getVisitorsCount', adminController.getVisitorsCount);
router.get('/getAppsCount', adminController.getAppsCount);

module.exports = router;
